# -*- coding: utf-8 -*-
"""Лабораторная №1.

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e0DEzaYWaHIBa5XlvnJiswe1ES1BlV6S

#Лабораторная работа №1
"""

a=5
b=6
c=a+b
print(c)

a=7.5
b=7.5
s=(a*a-b*b/4)/2
print(s)

a=3
b=4
c=5
x=(a**2+b**2-c**3)/2
print(x)

a=5
b=int(input())
c=a*b
print(c)

a=int(input())
b=int(input())
c=((a**3+14)/5)*b
print(c)

a=int(input())
b=int(input())
n=(a+b)**2
print(n)

a=15
b=10
c=int(input())
z=(a+b)/c
print(z)

a=int(input())
b=int(input())
c=(a**2+b**2)
print(c)

a=int(input()) 
b=int(input()) 
c=int(input()) 
s=a+b+c 
p=(a+b+c)/2 
print(s) 
print(p)

m=int(input()) 
x=m**2 
print(x) 
n=int(input()) 
z=x//n 
print(z)

a=int(input()) 
b=int(input()) 
z=a//b 
x=a+b 
c=a/b
print(z) 
print(x) 
print(c)

с=int(input()) 
м=с/60 
print(м) 
ч=м/60
print(ч) 
д=ч/24
print(д)